# items_to_remove = ['x2F', 'Onsite', 'ONSITE', 'Ruby', 'Django', 'Angular', 'Ops', 'Rails',
#                    'Remote', "REMOTE", 'Dev', 'Web', 'Senior', 'CTO', 'Business Operations',
#                    'INC', 'Roles', 'Lead', 'Saas', 'runway', 'Don', 'Sales Manager Akademie',
#                    'Grab', 'Iron', 'Norge', 'Metrics', 'Lyric', 'Labs', 'Web', 'APIS',
#                    'Security', 'Mobile', 'Robotics', 'Software', 'Mapbox', 'Admin', 'LABS',
#                    'Ys', 'Bus', 'Visa', 'Ai', 'Switch', 'Fulltime', 'Eng', 'DOE', 'Splunk',
#                    'Agency', 'WATCHMAN', 'Fabric', 'Here', 'Front', 'checker', 'MongoDB', 'Sales',
#                    'Jane', 'Designer', 'Accenture', 'Docker', 'Farmer', 'Phantom', 'Internet',
#                    'Logic', 'computer vision', 'Java', 'Atlas', 'Adara', 'backend loop', 'Fraze',
#                    'Apple', 'The Network', 'General Manager Office', 'Frontend Engineer', 'PHD',
#                    'Intermediate course', 'Dragon', 'The Front', 'MUST', 'PayPal', 'Daily',
#                    'Engineer', 'Amazon Web Services', 'Engineers', 'Contract', 'Microsoft',
#                    'Full', 'The Monkey', 'INC', 'Relic', 'Details', 'IOS', 'Data', 'Digital',
#                    'Developer', 'Networks']

